In [2]:
import pandas as pd

In [3]:
DATA_URL = ('https://s3-us-west-2.amazonaws.com/'
            'streamlit-demo-data/uber-raw-data-sep14.csv.gz')

In [5]:
data = pd.read_csv(DATA_URL, nrows=10)

In [6]:
data

Date/Time      Lat      Lon    Base
0  9/1/2014 0:01:00  40.2201 -74.0021  B02512
1  9/1/2014 0:01:00  40.7500 -74.0027  B02512
2  9/1/2014 0:03:00  40.7559 -73.9864  B02512
3  9/1/2014 0:06:00  40.7450 -73.9889  B02512
4  9/1/2014 0:11:00  40.8145 -73.9444  B02512
5  9/1/2014 0:12:00  40.6735 -73.9918  B02512
6  9/1/2014 0:15:00  40.7471 -73.6472  B02512
7  9/1/2014 0:16:00  40.6613 -74.2691  B02512
8  9/1/2014 0:32:00  40.3745 -73.9999  B02512
9  9/1/2014 0:33:00  40.7633 -73.9773  B02512

In [9]:
lat = 33.5934
start_point = -101.9029
end_point = -101.9014

In [10]:
import numpy as np

num_points = 96
points = np.linspace(start_point, end_point, num_points)

In [11]:
points

array([-101.9029    , -101.90288421, -101.90286842, -101.90285263,
       -101.90283684, -101.90282105, -101.90280526, -101.90278947,
       -101.90277368, -101.90275789, -101.90274211, -101.90272632,
       -101.90271053, -101.90269474, -101.90267895, -101.90266316,
       -101.90264737, -101.90263158, -101.90261579, -101.9026    ,
       -101.90258421, -101.90256842, -101.90255263, -101.90253684,
       -101.90252105, -101.90250526, -101.90248947, -101.90247368,
       -101.90245789, -101.90244211, -101.90242632, -101.90241053,
       -101.90239474, -101.90237895, -101.90236316, -101.90234737,
       -101.90233158, -101.90231579, -101.9023    , -101.90228421,
       -101.90226842, -101.90225263, -101.90223684, -101.90222105,
       -101.90220526, -101.90218947, -101.90217368, -101.90215789,
       -101.90214211, -101.90212632, -101.90211053, -101.90209474,
       -101.90207895, -101.90206316, -101.90204737, -101.90203158,
       -101.90201579, -101.902     , -101.90198421, -101.90196

In [12]:
array = np.full(10, 32)
array

array([32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

In [17]:
DATA_COLUMN = 'yield'
# DATA_URL = ('https://s3-us-west-2.amazonaws.com/'
#             'streamlit-demo-data/uber-raw-data-sep14.csv.gz')
DATA_FILE_PATH = 'my_cotton_yield_data.csv'


data = pd.read_csv(DATA_FILE_PATH, nrows=96)

In [18]:
data

red     green      blue  mask_size  irrigation  canopy_cover  \
0   0.329286  0.462679  0.451250   0.227679         0.0      0.104259   
1   0.340893  0.475000  0.465179   0.215893         0.0      0.098662   
2   0.346607  0.485000  0.468036   0.199643         0.0      0.102917   
3   0.349821  0.491071  0.470357   0.220179         0.0      0.117240   
4   0.353214  0.493929  0.478393   0.225357         0.0      0.113565   
..       ...       ...       ...        ...         ...           ...   
91  0.367857  0.505893  0.483750   0.274821         0.0      0.142624   
92  0.371429  0.508929  0.488929   0.266250         0.0      0.145176   
93  0.372143  0.511250  0.491786   0.257321         0.0      0.132355   
94  0.374107  0.515357  0.495536   0.253750         0.0      0.140910   
95  0.367679  0.507143  0.485357   0.263571         0.0      0.143268   

    canopy_height  canopy_volume  exgreeness  yield  
0        0.234420       0.021937    0.014248   21.2  
1        0.229882       0.019589    0.011565   21.6  
2        0.223200       0.015848    0.016326   16.9  
3        0.242145       0.021733    0.018544   21.3  
4        0.243106       0.021074    0.017271   20.9  
..            ...            ...         ...    ...  
91       0.368069       0.122611    0.021701   19.0  
92       0.359540       0.126751    0.018826   18.1  
93       0.351349       0.119836    0.020097   15.8  
94       0.350794       0.127022    0.018461   18.6  
95       0.352671       0.125125    0.020260   20.2  

[96 rows x 10 columns]

In [19]:
# A demo, change the lat, lon, in the future.
lat = 33.5934
start_point = -101.9029
end_point = -101.9014
num_points = 96

points = np.linspace(start_point, end_point, num_points)

data['lon'] = points
data['lat'] = np.full(num_points, lat)

In [22]:
import streamlit as st
st.map(data)

DeltaGenerator()

In [20]:
data

red     green      blue  mask_size  irrigation  canopy_cover  \
0   0.329286  0.462679  0.451250   0.227679         0.0      0.104259   
1   0.340893  0.475000  0.465179   0.215893         0.0      0.098662   
2   0.346607  0.485000  0.468036   0.199643         0.0      0.102917   
3   0.349821  0.491071  0.470357   0.220179         0.0      0.117240   
4   0.353214  0.493929  0.478393   0.225357         0.0      0.113565   
..       ...       ...       ...        ...         ...           ...   
91  0.367857  0.505893  0.483750   0.274821         0.0      0.142624   
92  0.371429  0.508929  0.488929   0.266250         0.0      0.145176   
93  0.372143  0.511250  0.491786   0.257321         0.0      0.132355   
94  0.374107  0.515357  0.495536   0.253750         0.0      0.140910   
95  0.367679  0.507143  0.485357   0.263571         0.0      0.143268   

    canopy_height  canopy_volume  exgreeness  yield         lon      lat  
0        0.234420       0.021937    0.014248   21.2 -101.902900  33.5934  
1        0.229882       0.019589    0.011565   21.6 -101.902884  33.5934  
2        0.223200       0.015848    0.016326   16.9 -101.902868  33.5934  
3        0.242145       0.021733    0.018544   21.3 -101.902853  33.5934  
4        0.243106       0.021074    0.017271   20.9 -101.902837  33.5934  
..            ...            ...         ...    ...         ...      ...  
91       0.368069       0.122611    0.021701   19.0 -101.901463  33.5934  
92       0.359540       0.126751    0.018826   18.1 -101.901447  33.5934  
93       0.351349       0.119836    0.020097   15.8 -101.901432  33.5934  
94       0.350794       0.127022    0.018461   18.6 -101.901416  33.5934  
95       0.352671       0.125125    0.020260   20.2 -101.901400  33.5934  

[96 rows x 12 columns]

In [25]:
np.random.rand(1000, 4).shape

(1000, 4)

In [26]:
np.random.randint(0, 3, 50)

array([1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 1,
       2, 0, 0, 2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0,
       1, 0, 1, 2, 1, 0])